"""v5_1_empire.py — AI Empire Factory v5.1 全自动引擎

每天 02:00 由 GitHub Actions 触发：
1. 拉 GitHub trending top 5 (stars > 30k)
2. AI 选 1 个最适合做 SaaS 的项目
3. 生成完整可运行项目骨架 (README + index.html + 1 个核心 .py)
4. 自动 commit + push
5. 触发 Vercel deploy hook

约束（避免被风控）：
- 每天只生 1 个
- 每个仓 ≤1 commit/天
- 产物简单（≤500 行）
- 不进 keys/ downloads/ 等敏感目录
"""
import os
import json
import datetime
import urllib.request
import urllib.error
from pathlib import Path
from urllib.parse import urlencode

GH_API = "https://api.github.com"
OPENAI_BASE = "https://api.minimaxi.com/anthropic"  # 默认 MiniMax 官方（Anthropic Messages API 兼容）
SCRIPT_DIR = Path(__file__).resolve().parent
OUT_BASE = SCRIPT_DIR  # 仓根目录（GitHub Actions 跑时即此；本地 monorepo 也同此）
TODAY = datetime.date.today().isoformat()
PROJECT_SLUG = f"v51-auto-{TODAY}"


def gh_get(path):
    req = urllib.request.Request(GH_API + path, headers={
        "Accept": "application/vnd.github+json",
        "X-GitHub-Token": os.environ.get("GITHUB_TOKEN", ""),
    })
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())


def fetch_top(n=5):
    params = urlencode({"q": "stars:>30000", "sort": "stars", "order": "desc", "per_page": n})
    data = gh_get(f"/search/repositories?{params}")
    return data.get("items", [])[:n]


def ai_pick(projects):
    """用 AI 选 1 个最适合做 SaaS 的项目"""
    key = os.environ.get("OPENAI_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN", "")
    if not key:
        # 无 key 时退化：用 stars 最高的
        return projects[0]
    body = json.dumps({
        "model": "MiniMax-M3",
        "max_tokens": 50,
        "messages": [{
            "role": "user",
            "content": f"从以下 GitHub 仓库选 1 个最适合做 SaaS 的（流量大 + 有商业化空间 + 不违法）。只返回 owner/repo 格式，不要其他内容。\n\n{[p['full_name'] for p in projects]}"
        }],
    }).encode()
    req = urllib.request.Request(f"{OPENAI_BASE}/v1/messages", data=body, headers={
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            j = json.loads(r.read())
            return j["content"][0]["text"].strip()
    except Exception:
        return projects[0]


def gen_scaffold(repo):
    """生成 1 个最小可运行项目骨架"""
    return {
        "README.md": f"""# {repo}

> Auto-generated by AI Empire Factory v5.1 on {TODAY}
> Source: https://github.com/{repo}
> Stars: trending top 5 at generation time

## 这是什么
基于 **{repo}** 的简化复刻 / 包装站。

## 部署
- 推到 GitHub 即可自动 Gitee Pages
- 详情见 v5.1 workflow

## License
MIT
""",
        "index.html": f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>{repo} · AI Empire v5.1</title>
<style>
body {{ font-family: sans-serif; max-width: 720px; margin: 40px auto; padding: 0 20px; color: #222; }}
h1 {{ color: #5865F2; }}
.badge {{ background: #22C55E; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px; }}
</style>
</head>
<body>
<h1>{repo}</h1>
<p><span class="badge">v5.1 auto</span> 生成于 {TODAY}</p>
<p>源仓库：<a href="https://github.com/{repo}" target="_blank">github.com/{repo}</a></p>
<hr>
<p><small>Powered by AI Empire Factory v5.1</small></p>
</body>
</html>
""",
        "v51_info.json": json.dumps({
            "generated_at": TODAY,
            "source_repo": repo,
            "version": "5.1",
            "trigger": "github-actions-cron",
        }, ensure_ascii=False, indent=2),
    }


def main():
    print(f"[v5.1] {TODAY} start")
    projects = fetch_top(5)
    if not projects:
        print("[v5.1] FAIL: 没拉到 trending")
        return 1
    print(f"[v5.1] fetched {len(projects)} trending repos")
    pick = ai_pick(projects)
    if isinstance(pick, dict):
        pick = pick.get("full_name", str(pick))
    print(f"[v5.1] picked: {pick}")
    files = gen_scaffold(pick)
    out_dir = OUT_BASE / PROJECT_SLUG
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (out_dir / name).write_text(content, encoding="utf-8")
    print(f"[v5.1] wrote {len(files)} files to {out_dir}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
